### ISSUE TITLE
All todo's here

### ISSUE THREAD

**Issue by nimit2801** [DSCNUV/Application-Portal#2]
Porting an app from HC to DSC

- [x] UI change 
- [x] metadata change
- [x]  deploy on Heroku
- [x]  create a database for DSC
- [x]  connect to the database
- [x]  use a new type form link
- [x]  complete type form port
- [x]  Add webhook and use it with the app
- [x]  Replace HC with DSC
- [x]  Release a Tag

**Comment by nimit2801** [comment]
> 
> 
> Porting an app from HC to DSC
> 
>     * [x]  UI change
> 
>     * [x]  metadata change
> 
>     * [x]   deploy on Heroku
> 
>     * [x]   create a database for DSC
> 
>     * [x]   connect to the database
> 
>     * [x]   use a new type form link
> 
>     * [x]   complete type form port
> 
>     * [x]   Add webhook and use it with the app
> 
>     * [x]   Replace HC with DSC
> 
>     * [x]   Release a Tag

All things completed here :D
Everything LGTM 👍 
Feel free to reopen if any changes needed 🌈
